spring:
  application:
    name: hexlet-blog
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
    show-sql: false
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

app:
  welcome-message: Welcome to Spring Boot!

logging:
  level:
    root: INFO
    io.hexlet.blog: DEBUG
    org.springframework.web: INFO
    org.hibernate: WARN

server:
  port: 8080
  error:
    include-message: always
